import { TabNavigator } from './src/navigation/TabNavigator';
import { DreamDetailScreen } from './src/screens/DreamDetailScreen';
import { CommunityProfileScreen } from './src/screens/CommunityProfileScreen';
import { CommunityPostDetailScreen } from './src/screens/CommunityPostDetailScreen';
import { NotificationsScreen } from './src/screens/NotificationsScreen';
import { SavedDreamsScreen } from './src/screens/SavedDreamsScreen';
import { EditProfileScreen } from './src/screens/EditProfileScreen';
import { PrivacyScreen } from './src/screens/PrivacyScreen';
import { HelpSupportScreen } from './src/screens/HelpSupportScreen';
console.log("TESTING EXPORTS:");
console.log("TabNavigator", typeof TabNavigator);
console.log("DreamDetailScreen", typeof DreamDetailScreen);
console.log("CommunityProfileScreen", typeof CommunityProfileScreen);
console.log("CommunityPostDetailScreen", typeof CommunityPostDetailScreen);
console.log("NotificationsScreen", typeof NotificationsScreen);
console.log("SavedDreamsScreen", typeof SavedDreamsScreen);
console.log("EditProfileScreen", typeof EditProfileScreen);
console.log("PrivacyScreen", typeof PrivacyScreen);
console.log("HelpSupportScreen", typeof HelpSupportScreen);
