"""add_analysis_json

Revision ID: 05e2a82421f5
Revises: 9fd890e45d20
Create Date: 2026-03-29 21:00:02.062119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = '05e2a82421f5'
down_revision = '9fd890e45d20'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dreams', sa.Column('analysis_json', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dreams', 'analysis_json')
    # ### end Alembic commands ###

