"""Add users table

Revision ID: 4223b796b07e
Revises: 20260324_0001
Create Date: 2026-03-29 19:17:14.225004

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '4223b796b07e'
down_revision = '20260324_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

