"""Add users table

Revision ID: 9fd890e45d20
Revises: 20260324_0001
Create Date: 2026-03-29 19:20:05.982090

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '9fd890e45d20'
down_revision = '20260324_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    
    # Insert default user to satisfy foreign key constraints for existing data
    op.execute("INSERT IGNORE INTO users (id, username, email) VALUES ('demo-user-001', 'Demo User', 'demo@example.com')")
    
    op.create_foreign_key('fk_dreams_user_id', 'dreams', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dreams', type_='foreignkey')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

